apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-secret
  namespace: secret-volume

spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04

    command:
      - sleep
      - "3600"

    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
      readOnly: true

  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret
